config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :searches, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/search_controller.rb
# app/controllers/search_controller.rb
class SearchController < ApplicationController

  def search
    @result = Searchable::Search.invoke(search_params)
  rescue => exc
    @result = { error: true }
  ensure
    respond_to do |format|
      format.html
      format.js
    end
 end

  private

  def search_params
    params.require(:q)
  end

end

app/controllers/searches_controller.rb
# /app/controllers/search_controller.rb

class SearchesController < ApplicationController
  def create
    @result = Searchable::SearchService.invoke(search_params)
  rescue => exc
    puts exc.message
    @result = { error: true }
  ensure
    respond_to do |format|
      format.html
      format.js
    end
  end

  def  new

  end

  private

  def search_params
    params.require(:q)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Searchable</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/search/_search_error.html.erb
<div class ='search-error'><h2>Sorry! Something went wrong :(</h2></div>

app/views/search/_search_result.html.erb
<% items.each do |item| %>
    <div class="search-result">
      <p><div class='search-result-name'><b><%= item['name'] %></b></div></p>
      <p><div class='search-result-type'><b>Type:</b> <%= item['type'] %></div></p>
      <p><div class='search-result-designed-by'><b>Designed by:</b>  <%= item['designed by'] %></p></div>
    </div>
<% end %>

app/views/search/_search_results.html.erb
<% if result[:full_match].present? %>
    <%= render(partial: 'search_result', locals: { items: result[:full_match] }) %>
    <% if @result[:other_results].present? %>
        <div class ='search-other-result-label'><h2>You may also be interested in:</h2></div>
        <div class ='search-other-results'>
          <%= render(partial: 'search_result', locals: { items: result[:other_results] }) %>
        </div>
    <% end %>
<% else %>
    <div class="empty-search-result"><h2>Sorry, we didn't find anything</h2></div>
<% end %>

app/views/search/new.html.erb
<div class="container">
  <div class="form-container">
    <%= form_tag(search_path, id: 'search-form-wrapper', remote: true) do %>
        <%= label_tag(:q, 'Search for:') %>
        <%= text_field_tag :q, '', required: true %>
        <%= submit_tag('Search') %>
    <% end %>
  </div>
  <div id = 'search-results'></div>
</div>

app/views/search/search.js.erb
<% if @result[:error].present? %>
  $('#search-results').html("<%= j render(partial:'search_error')  %>")
<% else %>
  $('#search-results').html("<%= j render(partial:'search_results', locals: { result: @result }) %>")
<% end %>

app/views/searches/_search_result.html.erb
<% items.each do |item| %>
    <%= puts item.inspect %>
    <%= puts item['name'] %>
    <div class="search-result">
<p><div class='search-result-name'><b><%= item['name'] %></b></div></p>
      <p><div class='search-result-type'><b>Type:</b> <%= item['type'] %></div></p>
      <p><div class='search-result-designed-by'><b>Designed by:</b>  <%= item['designed_by'] %></p></div>
    </div>
<% end %>

app/views/searches/_search_results.html.erb
<%= render(partial: 'search_result', locals: { items: result }) %>

app/views/searches/create.js.erb
$('#search-results').html("<%= j render(partial:'search_results', locals: { result: @result[:full_match] }) %>")

app/views/searches/new.html.erb
<div class="container">
  <div class="form-container">
    <%= form_tag(searches_path, id: 'search-form-wrapper', method: :post, remote: true) do %>
        <%= label_tag(:q, 'Search for:') %>
        <%= text_field_tag :q, '', required: true %>
        <%= submit_tag('Search') %>
    <% end %>
  </div>
  <div id = 'search-results'></div>
</div>